- asdf:
  - plugin: python
    url: https://github.com/danhper/asdf-python.git
    global: 3.7.8
    versions:
      - 3.7.8
      - 3.6.1
  - plugin: ruby
    url: https://github.com/asdf-vm/asdf-ruby.git
    global: 2.6.5
    versions:
      - 2.6.5
  - plugin: neovim
    url: https://github.com/richin13/asdf-neovim.git
    global: nightly
    versions:
      - nightly
