- brew:
    - tmux

# Setup tpm : tmux plugin manager
- create:
    - ~/.tmux/plugins

- link:
    ~/.tmux.conf:
      path: tmux/.tmux.conf
    ~/.tmux.conf.local:
      path: tmux/.tmux.conf.local

- shell:
    - description: Clone tpm
      quiet: true
      command: |
        if cd ~/.tmux/plugins/tpm;
        then git pull;
        else git clone https://github.com/tmux-plugins/tpm.git ~/.tmux/plugins/tpm;
        fi
