# Colors (City Lights Theme)
colors:
  # Default colors
  primary:
    background: "0x1D252C"
    foreground: "0xA0B3C5"

  # Normal colors
  normal:
    black: "0x41505E"
    red: "0xD95468"
    green: "0x8BD49C"
    yellow: "0xEBBF83"
    blue: "0x5EC4FF"
    magenta: "0xE27E8D"
    cyan: "0x70E1E8"
    white: "0x9CAABB"

  # Bright colors
  bright:
    black: "0x41505E"
    red: "0xff6655"
    green: "0x99bb66"
    yellow: "0xEEBB88"
    blue: "0x539AFC"
    magenta: "0xEE7788"
    cyan: "0x77EEEE"
    white: "0xAABBCC"
