#!/bin/sh
export IDEA_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/idea.vmoptions"
export CLION_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/clion.vmoptions"
export PHPSTORM_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/phpstorm.vmoptions"
export GOLAND_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/goland.vmoptions"
export PYCHARM_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/pycharm.vmoptions"
export WEBSTORM_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/webstorm.vmoptions"
export WEBIDE_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/webide.vmoptions"
export RIDER_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/rider.vmoptions"
export DATAGRIP_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/datagrip.vmoptions"
export RUBYMINE_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/rubymine.vmoptions"
export APPCODE_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/appcode.vmoptions"
export DATASPELL_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/dataspell.vmoptions"
export GATEWAY_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/gateway.vmoptions"
export JETBRAINS_CLIENT_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/jetbrains_client.vmoptions"
export JETBRAINSCLIENT_VM_OPTIONS="/Users/eqielb/Documents/JaNetfilter/vmoptions/jetbrainsclient.vmoptions"
