# zsh load env via this order: 
# `.zshenv → .zprofile → .zshrc → .zlogin → .zlogout`
# it will inject 
# `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:` 
# into your system PATH at the beginning of zprofile (or the end of zshenv).

# echo "init zlogout"
