#!/usr/bin/env zsh

# This script removes folder from PATH variable
# Folders to remove reading as arguments

if [ $# -lt 1 ]; then
    echo "You should give at least one argument"
    echo "For example: unexport \$(brew --prefix)/bin or eval \"\$(unexport \$(brew --prefix)/bin)\""
else
    FOLDERS_TO_REMOVE=`echo $@ | sed 's/ /|/g'`

    # echo "You actually PATH variable is:"
    # echo $PATH

    PATH=$( echo ${PATH} | tr -s ":" "\n" | grep -vwE "(${FOLDERS_TO_REMOVE})" | tr -s "\n" ":" | sed "s/:$//" )

    # echo "Now you need to place the following line in a script or run in your terminal."

    echo "export PATH=$PATH"
fi
