tap "buo/cask-upgrade"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask-versions"
tap "beeftornado/rmtree"
tap "dteoh/sqa"
tap "homebrew/bundle"
tap "romkatv/powerlevel10k"


brew "romkatv/powerlevel10k/powerlevel10k"

# brew "hexyl"
# brew "xsv"
# brew "hledger"
